### ISSUE TITLE
6 september

### ISSUE THREAD

**Issue by AhmedNazirMusah** [AhmedNazirMusah/myPortfolio#9]

**Comment by arabiu033** [comment]
Add some paddings in the about me mobile version design. it will greatly help with the design.
The nav links are not responding. I feel it will greatly help with the page accessibility.

**Comment by amon-cofie** [comment]
Great work on making the page look just like the template on figma 👍 . I noticed that when I hover over the buttons the dimensions of the other parts of your page shift out of position a little bit. If that is fixed then your work would be flawless 💪

**Comment by AhmedNazirMusah** [comment]
Thanks for your feedback.
